import { test, expect } from '@playwright/test'
import { api, conversation, createGeoProject, finalized, report, send } from './helpers'

test('Geo report upload, two versions, reload and independent conversations', async ({ page }) => {
  const project = await createGeoProject(page)
  await page.locator('details.input-files summary').click()
  const uploaded = page.waitForResponse(r => r.url().endsWith(`/projects/${project}/inputs`) && r.request().method() === 'POST')
  await page.locator('input[type=file]').setInputFiles('fixtures/locations.csv')
  expect((await uploaded).status()).toBe(201)
  await expect(page.getByText('locations.csv', { exact: true })).toBeVisible()
  const first = await conversation(page)
  const second = await conversation(page)
  await page.locator(`a[href="/projects/${project}/conversations/${first}"]`).click()
  const run1 = await send(page, 'geo-report')
  await finalized(page, run1)
  await expect(page.locator(`[data-run-id="${run1}"] summary`)).toHaveText('Write report 完成')
  const original = await report(page)
  const js = await page.request.get(new URL('vendor/echarts.min.js', original).href)
  expect(js.headers()['content-type']).toMatch(/javascript/)
  expect(js.headers()['x-content-type-options']).toBe('nosniff')
  const run2 = await send(page, 'success-v2')
  await finalized(page, run2)
  const updated = await report(page, 'Geographic report v2')
  expect(updated).not.toBe(original)
  expect(run2).not.toBe(run1)
  await page.getByLabel('制品版本').selectOption(run1)
  expect(await report(page)).toBe(original)
  const runsRead = page.waitForResponse(r => r.url().endsWith(`/conversations/${first}/runs`))
  await page.reload()
  expect((await (await runsRead).json()).map((r: any) => r.id)).toEqual([run1, run2])
  expect(await report(page)).toBe(original)
  await expect(page.locator('[data-run-id]')).toHaveCount(2)
  await page.locator(`a[href="/projects/${project}/conversations/${second}"]`).click()
  const independent = await send(page, 'geo-report')
  await finalized(page, independent)
  expect((await api(page, `/runs/${independent}`)).body.source_sdk_session_id).toBeNull()
  await expect(page.locator('[data-run-id]')).toHaveCount(1)
  await expect(page.locator(`[data-run-id="${run1}"]`)).toHaveCount(0)
  await page.locator(`a[href="/projects/${project}/conversations/${first}"]`).click()
  await expect(page.locator('[data-run-id]')).toHaveCount(2)
  await expect(page.locator(`[data-run-id="${independent}"]`)).toHaveCount(0)
})
